services:
  backend-flask:
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      HONEYCOMB_API_KEY: "8PGvHyKZhUGUuuJRyFeefC"
      HONEYCOMB_DATASET: "test-dataset"  # Make sure this matches your working dataset!
      OTEL_SERVICE_NAME: "backend-flask"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io:443/v1/traces"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=hcaik_01jjhk4hywsfp4qaengzbzd5rf"
      AWS_XRAY_URL: "*4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}*"
      AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"  # Update this!
      AWS_REGION: "us-east-1"  # Set your AWS region
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    depends_on:
      - xray-daemon 

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js/src:/frontend-react-js/src
      - ./frontend-react-js/public:/frontend-react-js/public
      - ./frontend-react-js/package.json:/frontend-react-js/package.json
      - ./frontend-react-js/package-lock.json:/frontend-react-js/package-lock.json
  xray-daemon:
    image: amazon/aws-xray-daemon:latest
    restart: always
    ports:
      - "2000:2000/udp"  # matches AWS_XRAY_DAEMON_ADDRESS
    command: 
      - "-o"    # Enable local mode (important for Gitpod)
      - "-b"    # Bind to all interfaces
      - "0.0.0.0:2000"  # Bind to the correct address      

    environment:
      - AWS_REGION=us-east-1  # AWS Region is explicitly set
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    networks:
      - interval-network

  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

networks:
  interval-network:
    driver: bridge
    name: cruddur

volumes:
  db:
    driver: local
