services:
  backend-flask:
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      HONEYCOMB_API_KEY: "8PGvHyKZhUGUuuJRyFeefC"
      HONEYCOMB_DATASET: "test-dataset"
      OTEL_SERVICE_NAME: "backend-flask"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io:443/v1/traces"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=hcaik_01jjhk4hywsfp4qaengzbzd5rf"
      AWS_XRAY_URL: "*4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}*"
      AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"  # Use service name, not static IP
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    depends_on:
      - xray-daemon 
    networks:
      - aws-bootcamp-cruddur-2023_aws-bootcamp-cruddur-2023_cruddur

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js/src:/frontend-react-js/src
      - ./frontend-react-js/public:/frontend-react-js/public
      - ./frontend-react-js/package.json:/frontend-react-js/package.json
      - ./frontend-react-js/package-lock.json:/frontend-react-js/package-lock.json

  xray-daemon:
    image: amazon/aws-xray-daemon:latest
    restart: always
    ports:
      - "2000:2000/udp"
      - "2000:2000/tcp"
    command: 
      - "-o"   # Enable local mode
      - "-n"   # Send traces to AWS
      - "-b"   # Bind to all interfaces
      - "0.0.0.0:2000" 
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - aws-bootcamp-cruddur-2023_aws-bootcamp-cruddur-2023_cruddur

  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

networks:
  aws-bootcamp-cruddur-2023_aws-bootcamp-cruddur-2023_cruddur:
    driver: bridge


volumes:
  db:
    driver: local
